### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by jim-rosales** [pet527823/prj-rev-bwfs-dasmoto#5]
Grade: Meets Expectations

Summary:
Peter, great job on finishing the Dasmoto project! You did an excellent job making sure your HTML file was readable by using whitespace appropriately to separate out various section and by commenting throughout the file. You also did a marvelous job of reducing duplicate CSS in your file by applying universal styles.

The only syntax error I noticed was not using entity references as discussed in issue #1. This is a small syntax mistake although it is straightforward to fix and keep in mind while you work on future projects. This [reference](https://dev.w3.org/html5/html-author/charref) might help you find the codes for other commonly used symbols.

As a challenge and for extra practice consider using [linear gradient](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient) in your project. This will allow you to add a unique look to your project.

**Comment by pet527823** [comment]
Thank you so much for your response. I was not aware of the entity references issue, and I will look into that. It was not highlighted anywhere in the Codecademy coursework, so I will suggest it to them. Thanks again.
